### ISSUE TITLE
Password Validation Component Request

### ISSUE THREAD

**Issue by frankverhorst** [bettyblocks/material-ui-component-set#217]
Many websites and applications need some form (no pun intended) of a 'reset/new password' flow.

It would be nice to have a default component that validates on the frontend if these 2 password match and are strong enough.

Example: https://prnt.sc/su8z3s

**Comment by vdberganton** [comment]
Hi Frank, 

Seeing this is flow is made out of multiple components the best way to resolve this is by using an interaction between two components. This is something one of our teams is currently working on so that will be available via interactions in the future.

We will not create a default component for this!
