### ISSUE TITLE
Icon for prefab not supported

### ISSUE THREAD

**Issue by Steveennn** [bettyblocks/material-ui-component-set#392]
In an attempt to make this repo work on a windows device I took the src folder an moved it the the repo I get when running **bb components create hello-world.** I also made sure to add the dependencies to the package.json and run $ bb components create hello-world So far so good.
When I try to **npm run dev** however I get the following error: 

> Error: 
Property: "icon" must be one of [AccordionIcon, AccordionItemIcon, .... ] at prefab: Avatar

The icon thats used in the Avatar prefab is `icon: 'AvatarIcon',`
I tried replacing all icons where I get this error whit a valid one (ButtonIcon in this case) and then I can run **npm run dev** with no errors.

How can I fix this and still keep the icons, or is this a stupid attempt at making it work on windows?

**Comment by roy-willemse** [comment]
@Steveennn which version of the CLI are you using? You can check this by running:
`bb components -V`

I had this issue before as well and for me it was fixed when I installed version: 22.29.0
`npm install -g @betty-blocks/cli@22.29.0`

This is not ideal because you don't get the latest features in the IDE but you can build your components.

**Comment by Steveennn** [comment]
@roy-willemse I am on 23.9.0

**Comment by roy-willemse** [comment]
@Steveennn Did you try the version I suggested as a temporary workaround?

**Comment by Steveennn** [comment]
@roy-willemse I have not, because every time I try this ik stays on version 23.9.0

**Comment by nulian** [comment]
This repo should work now on windows.
